server:
  port: 8082
  
spring:
  application:
    name: classroom-school
  datasource:
    url: jdbc:mysql://172.17.0.3/school
    username: schoolservice
    password: Aq1sw2de3fr4
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show-sql: true
    generate-ddl: false
    hibernate:
        ddl-auto: none
        naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
        hibernate.hbm2ddl.auto: validate    

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/